# Generated by Django 2.0.4 on 2018-07-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetloginuser',
            name='private_key',
            field=models.FileField(blank=True, null=True, upload_to='upload/privatekey/%Y%m%d98689', verbose_name='私钥'),
        ),
    ]
